### ISSUE TITLE
Cannot be install in Ubuntu12.04 and ros hydro

### ISSUE THREAD

**Issue by AngelLovesDevil** [ros-drivers/openni_launch#24]
I firstly installed the hydro, then installed the standalone OpenNI and sensorKinect, but when i tried to install the openni_launch, i got the error messges:  
ros-hydro-openni-launch:  Depends: ros-hydro-openni-camera but it is not going to be installed, 
E: Unable to correct problems, you have held broken packages.

So I tried to install openni_camera firstly, but i also got some errors:
ros-hydro-openni-camera: Depends: libopenni0 but it is not going to be installed
                                           Depends: libopenni-dev but it is not going to be installed
                                           Depends: libopenni-sensor-primesense-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages/

So similarly I tried to install the libopenni0, libopenni-dev and libopenni-sensor-primesence-dev, this time it can be installed, but messges showed that it will removed some packages, including several ros related packages and pcl related packages. But i stll tried, after installation, i got big problems that the ros didn't run normally, possible like that my ros had been broken.

How can I fix this problem? please help! thanks in advance!
and the version of openni and sensor that i installed was v1.5.4.0 and v5.1.2.1 respectively.
Thanks!!!

**Comment by 130s** [comment]
I'm sorry for your issue, but your issue is clearly not rooted in `openni_launch` or not even ROS I believe. For that reason I'm closing the ticket.
I suggest you Google the error code (e.g. [this](https://www.google.com/search?client=ubuntu&channel=fs&q=E%3A+Unable+to+correct+problems%2C+you+have+held+broken+packages.&ie=utf-8&oe=utf-8). You'll get tons of helpful links).
