### ISSUE TITLE
How can I compile openni_launch and install into rgbdslam?

### ISSUE THREAD

**Issue by AngelLovesDevil** [ros-drivers/openni_launch#25]
this problem i had spent several time to sovle, but unfornately i didnot solve it out, so i came here.
thank you if you have time to tell me the way to do it!

**Comment by 130s** [comment]
Could you elaborate what you mean by "compile openni_launch and install into rgbdslam"? Otherwise I'm afraid if there's anyone who can assist you. I close this until you provide more info.
And, generally speaking in ROS, there's a very good forum http://answers.ros.org/ that is dedicated for questions.

**Comment by AngelLovesDevil** [comment]
Hello, thanks for replying! My original meaning was that if there is another way to use the openni_launch other than by installing it using the command "sudo apt-get install ros-hydro-openni-launch"? Thanks!

**Comment by jack-oquin** [comment]
You can build it (or any other ROS package) from source by putting it in your workspace along with whatever other packages you are building.

As Isaac said: http://answers.ros.org is the best place to resolve questions like yours. Good luck!
